### PR TITLE
Respect environment proxy settings

### PR DESCRIPTION
**Pull request by cyqsimon**
This permits compiling behind a firewall using a proxy gateway.

### CODE REVIEW

**Comment by cyqsimon** [comment]
This only allows the use of HTTP proxies, not SOCKS proxies, but at least it's better than nothing.

If you are okay with making changes to dependencies, it's easy to allow SOCKS proxies too. Simply enable the `socks-proxy` feature on `ureq`: see [ureq docs](https://docs.rs/ureq/latest/ureq/index.html#proxying).

**Comment by mdrokz** [comment]
hey @cyqsimon thanks for the PR and sorry for late reply can you resolve the conflicts i merged a new PR #5. once you resolve the conflicts i will merge this. Thanks!

**Review by mdrokz — APPROVED** [review]

**Comment by cyqsimon** [comment]
@mdrokz you're not late at all =). Rebased.

**Comment by mdrokz** [comment]
> @mdrokz you're not late at all =). Rebased.

Thanks this looks good to be merged.

**Comment by mdrokz** [comment]
> This only allows the use of HTTP proxies, not SOCKS proxies, but at least it's better than nothing.
> 
> If you are okay with making changes to dependencies, it's easy to allow SOCKS proxies too. Simply enable the `socks-proxy` feature on `ureq`: see [ureq docs](https://docs.rs/ureq/latest/ureq/index.html#proxying).

Can you create another PR for that ? I will review and merge it :) thanks

**Comment by cyqsimon** [comment]
I'll just push another commit onto this branch. It counts as one feature anyway.

**Comment by mdrokz** [comment]
> I'll just push another commit onto this branch. It counts as one feature anyway.

Ah ok makes sense i thought it was something else. Thanks i will merge this now

**Pull request merged**
